spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database-platform: H2
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  secret-word: newSecretJWT
  image-path: file/image